DEFAULT_COLMAP = [
    "Artnamn",
    "Lokalnamn",
    "Noggrannhet",
    "Ost",
    "Nord",
    "Startdatum",
    "Publik kommentar",
]

FULL_COL_LIST = [
    "Artnamn",
    "Antal",
    "Enhet",
    "Antal substrat",
    "Ålder-Stadium",
    "Kön",
    "Aktivitet",
    "Metod",
    "Lokalnamn",
    "Ost",
    "Nord",
    "Noggrannhet",
    "Diffusion",
    "Djup min",
    "Djup max",
    "Höjd min",
    "Höjd max",
    "Startdatum",
    "Starttid",
    "Slutdatum",
    "Sluttid",
    "Publik kommentar",
    "Intressant kommentar",
    "Privat kommentar",
    "Ej återfunnen",
    "Dölj fyndet t.o.m.",
    "Andrahand",
    "Osäker artbestämning",
    "Ospontan",
    "Biotop",
    "Biotop-beskrivning",
    "Art som substrat",
    "Art som substrat beskrivning",
    "Substrat",
    "Substrat-beskrivning",
    "Offentlig samling",
    "Privat samling",
    "Samlings-nummer",
    "Bestämningsmetod",
    "Artbestämd av",
    "Artbestämd av (fritext)",
    "Bestämningsår",
    "Beskrivning artbestämning",
    "Bekräftad av",
    "Bekräftad av (fritext)",
    "Bekräftelseår",
    "Länk till BOLD/GenBank",
    "Med-observatör",
    "Externid",
    "Ej funnen",
]

COLMAP = {
    "artnamn": "Artnamn",
    "antal": "Antal",
    "enhet": "Enhet",
    "antal substrat": "Antal substrat",
    "ålder-stadium": "Ålder-Stadium",
    "kön": "Kön",
    "aktivitet": "Aktivitet",
    "metod": "Metod",
    "lokalnamn": "Lokalnamn",
    "ost": "Ost",
    "nord": "Nord",
    "noggrannhet": "Noggrannhet",
    "diffusion": "Diffusion",
    "djup min": "Djup min",
    "djup max": "Djup max",
    "höjd min": "Höjd min",
    "höjd max": "Höjd max",
    "startdatum": "Startdatum",
    "starttid": "Starttid",
    "slutdatum": "Slutdatum",
    "sluttid": "Sluttid",
    "publik kommentar": "Publik kommentar",
    "intressant kommentar": "Intressant kommentar",
    "privat kommentar": "Privat kommentar",
    "ej återfunnen": "Ej återfunnen",
    "dölj fyndet t.o.m.": "Dölj fyndet t.o.m.",
    "andrahand": "Andrahand",
    "osäker artbestämning": "Osäker artbestämning",
    "ospontan": "Ospontan",
    "biotop": "Biotop",
    "biotop-beskrivning": "Biotop-beskrivning",
    "art som substrat": "Art som substrat",
    "art som substrat beskrivning": "Art som substrat beskrivning",
    "substrat": "Substrat",
    "substrat-beskrivning": "Substrat-beskrivning",
    "offentlig samling": "Offentlig samling",
    "privat samling": "Privat samling",
    "samlings-nummer": "Samlings-nummer",
    "bestämningsmetod": "Bestämningsmetod",
    "artbestämd av": "Artbestämd av",
    "artbestämd av (fritext)": "Artbestämd av (fritext)",
    "bestämningsår": "Bestämningsår",
    "beskrivning artbestämning": "Beskrivning artbestämning",
    "bekräftad av": "Bekräftad av",
    "bekräftad av (fritext)": "Bekräftad av (fritext)",
    "bekräftelseår": "Bekräftelseår",
    "länk till bold/genbank": "Länk till BOLD/GenBank",
    "med-observatör": "Med-observatör",
    "externid": "Externid",
    "ej funnen": "Ej funnen",
}
