DEFAULT_COLMAP = [
    "Artnamn",
    "Lokalnamn",
    "Noggrannhet",
    "Ost",
    "Nord",
    "Startdatum",
    "Publik kommentar",
]

FULL_COLMAP = [
    "Artnamn",
    "Antal",
    "Enhet",
    "Antal substrat",
    "Ålder-Stadium",
    "Kön",
    "Aktivitet",
    "Metod",
    "Lokalnamn",
    "Ost",
    "Nord",
    "Noggrannhet",
    "Diffusion",
    "Djup min",
    "Djup max",
    "Höjd min",
    "Höjd max",
    "Startdatum",
    "Starttid",
    "Slutdatum",
    "Sluttid",
    "Publik kommentar",
    "Intressant kommentar",
    "Privat kommentar",
    "Ej återfunnen",
    "Dölj fyndet t.o.m.",
    "Andrahand",
    "Osäker artbestämning",
    "Ospontan",
    "Biotop",
    "Biotop-beskrivning",
    "Art som substrat",
    "Art som substrat beskrivning",
    "Substrat",
    "Substrat-beskrivning",
    "Offentlig samling",
    "Privat samling",
    "Samlings-nummer",
    "Bestämningsmetod",
    "Artbestämd av",
    "Artbestämd av (fritext)",
    "Bestämningsår",
    "Beskrivning artbestämning",
    "Bekräftad av",
    "Bekräftad av (fritext)",
    "Bekräftelseår",
    "Länk till BOLD/GenBank",
    "Med-observatör",
    "Externid",
    "Ej funnen",
]
